### PR TITLE
Add accessibility note to interactivity section in the new React docs

### PR DESCRIPTION
**Pull request by kmiddleton14**
We want to add accessibility into the new React Docs. This PR adds a note in the interactivity section letting users know to use the html tag `<button>` instead of `<div>` when using onClick handlers.

Screenshot 2023-05-12 at 1 17 42 PM

### CODE REVIEW

**Review by jessebeach — COMMENTED** [review]
Makes sense and conforms to best practice recommendations.

**Comment by sophiebits** [comment]
This overview is really supposed to be a brief 1-minute summary of each page within the section. How about we instead add a note to the "Responding to Events" page at an appropriate place? 

I also noticed that the linked page is a little terse and jargony and I'm not sure that it is accessible (ha) to many of our site visitors. I found https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML which might be a better introductory resource to link to.

**Comment by kmiddleton14** [comment]
Added to the "Responding to Events" page and updated the link to https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML

**Comment by jessebeach** [comment]
Looks good. It conveys the right message.

**Pull request merged**
