### PR TITLE
docs: update branding in docs

### PR DESCRIPTION
**Pull request by asciidiego**
Super simple change.

### CODE REVIEW

**Comment by diegonyc** [comment]
@facebook-github-bot CLA signed.

**Comment by gaearon** [comment]
Seems like we'd want to do this consistently across other pages as well

**Comment by diegonyc** [comment]
> Seems like we'd want to do this consistently across other pages as well

Any way to find what pages are there? Some of them have a link with a "Facebook" label but those are links to, say, the React Facebook page. In those cases, I am assuming you would not want to change those.

Is there a way to find places where it makes sense to change it?

**Comment by gaearon** [comment]
Probably stuff in the `content` folder.

**Comment by BartoszKlonowski** [comment]
Dears, I went through the latest of react.dev searching for any mentions of "Facebook" instead of "Meta" and couldn't find any that wouldn't be valid URLs or mentions at that time.
So I think that we can safely close this PR as no longer required, but thanks @asciidiego for bringing this!

**Pull request closed without merging**
