### PR TITLE
Fix CSS discrepancy in issue #6508

### PR DESCRIPTION
**Pull request by DongHY1**
fix: #6508 

https://github.com/reactjs/react.dev/assets/73568310/b1018db5-df66-406d-98e8-fb3dbc32a28a

### CODE REVIEW

**Comment by DongHY1** [comment]
CLA signed done

**Comment by DongHY1** [comment]
@facebook-github-bot CLA signed.

**Comment by DongHY1** [comment]
cc @harish-sethuraman

**Review by rickhanlonii — APPROVED** [review]
Nice catch

**Pull request merged**
