### PR TITLE
Simplify by making the input field "number"

### PR DESCRIPTION
**Pull request by githubshrek**
If we make the input field of type="number" we can simplify the example a lot. This is good from two points of view:
a) it's the right thing to do, to make a number field of type number, and let the field itself handle the type restriction to numeric
b) it will help the user to focus on the real complexity of the example (which is moving the state up), since it removes a lot of the irrelevant clutter

### CODE REVIEW

**Comment by gaearon** [comment]
I think there was a reason why we did this but I struggle to recall it. There might've been some bug with controlled numeric inputs. Maybe it got fixed.

**Comment by gaearon** [comment]
Does the same sequence of steps that I do in the GIF at the end of the post work with this change?

**Comment by alexkrolick** [comment]
The old code might have been there to format the results:
> and it keeps the output rounded to the third decimal place

Doesn't seem super important to the overall example, though.

**Comment by githubshrek** [comment]
Incidentally, I have to thank the ReactJS documentation in fact for teaching me about the new with HTML5 "number" input type. The first time I had ever seen it was on the Quick Start -> Forms page, in the Reservation example.

**Comment by githubshrek** [comment]
I'm still quite new to the process here. Are these changes this planned to go live?

**Comment by BartoszKlonowski** [comment]
Dears! Looking at the latest docs, I see that the changes introduced in this PR are no longer needed, as there's no such code and page now in the docs.
Let me close this PR as outdated.

**Pull request closed without merging**
