### PR TITLE
Fix #6487 specify which `Sandpack` files go into a `src` directory

### LINKED ISSUE #6487: Sandpack examples with index.html files throw runtime errors
1. https://react.dev/learn/add-react-to-an-existing-project#step-2-render-react-components-anywhere-on-the-page
image
2. https://react.dev/reference/react-dom/createPortal#rendering-react-components-into-non-react-server-markup
image

The issue seems to be because the `index.html` files defined in these examples are not used, instead, the `public/index.html` defined in the [template](https://github.com/reactjs/react.dev/blob/e98c3939a7c55e0ba2f0ae5beba3b7a1298b8d23/src/components/MDX/Sandpack/template.ts#L40) are used

### PR DESCRIPTION
**Pull request by geeseyj**
Preface: #6487 

This PR removes the assumption that all `Sandpack` example files should be put into a `/src/` folder and instead does so explicitly on only that files that need it.

[preview](https://react-dev-git-fork-geeseyj-fix-sandpack-files-fbopensource.vercel.app/learn/add-react-to-an-existing-project#step-2-render-react-components-anywhere-on-the-page)

### CODE REVIEW

**Comment by mattcarrollcode** [comment]
@geeseyj Thanks for identifying and writing up a fix! This looks like a lot of monotonous work, thank you for doing this. The general approach looks good I'm taking a closer look now.

**Comment by geeseyj** [comment]
I just found a few stragglers 😅 🤦 un momento

**Review by mattcarrollcode — APPROVED** [review]
LGTM! Thanks, merging

**Comment by geeseyj** [comment]
Thanks!

> @geeseyj Thanks for identifying and writing up a fix! This looks like a lot of monotonous work, thank you for doing this. The general approach looks good I'm taking a closer look now.

Luckily regexr was able to help me out hah regexr.com/7p78p

**Pull request merged**
