### PR TITLE
Update to CodePen URL

### PR DESCRIPTION
**Pull request by chriscoyier**
Updating to [CodePen's official documented format](https://blog.codepen.io/documentation/templates/#api) for starting Pens with prefilled content. There is also [a Prefill API](https://blog.codepen.io/documentation/prefill/), but that requires a POST, so this URL format is easier to use. But it does require that there is already an existing Pen that it copies the content out of. The Pen in this PR is [this one](https://codepen.io/chriscoyier/pen/QWYVwWN) owned by me. I can promise I'll never update that Pen, but if you want to go with this approach, you might wanna update the "slug" to a Pen owned by React on CodePen. Let me know there are any questions!

### CODE REVIEW

**Comment by chriscoyier** [comment]
> In order to merge any pull request (code, docs, etc.), we require contributors to sign our Contributor License Agreement, and we don't seem to have one on file for you.

Done.

**Comment by chriscoyier** [comment]
Just checking in here. 

The link to CodePen [on this page](https://react.dev/learn/installation) 500 errors because of the invalid usage so it would be nice to fix. We have users writing in to tell us they are getting stuck by this.

**Comment by broofa** [comment]
@rickhanlonii @harish-sethuraman @jackpope :  Sorry for pinging you here, but I believe you three have recently merged PRs in this repo...? (Let me know if I have that wrong). I'm hoping one of you can provide some insight on what else we need to do to get this merged.

To be clear, we (CodePen) are trying to fix this user experience:

**Review by harish-sethuraman — APPROVED** [review]
Sorry missed this PR. I hope this pen is never removed.  We could also implement the codepen link using the prefill API in case there are chances in removal of the pen.

**Pull request merged**
