### PR TITLE
New Philly React meetup URL

### PR DESCRIPTION
**Pull request by pixelyunicorn**
RQ React meetup has been renamed to Reactadelphia

### CODE REVIEW

**Comment by lex111** [comment]
@pixelyunicorn Hmm, but RQ React also exists and organizes meetups, right?

**Comment by pixelyunicorn** [comment]
@lex111 The organizer of RQ React @DomitriusAnthony is rebranding the group as Reactadelphia and is post all future meetups under the new group

**Comment by lex111** [comment]
Maybe it makes sense on the "old" meetup page (https://www.meetup.com/RQ-React/) to post a message that there is now another page (Reactadelphia)?

**Comment by BartoszKlonowski** [comment]
I see this is already updated:
https://github.com/reactjs/react.dev/blob/e33ec30515561d715e35b2c437402c5c58d4ecd8/src/content/community/meetups.md?plain=1#L208
So let me close this as outdated.

**Pull request closed without merging**
