### PR TITLE
Added Gatsby Redirects for Versioned Documentations

### PR DESCRIPTION
**Pull request by manishprivet**
I couldn't find anything related to docs on specific versions present in `/versions`, and the `/version/:version_number` was going to a broken link as mentioned in this [issue](https://github.com/reactjs/reactjs.org/issues/3268).

### CODE REVIEW

**Comment by manishprivet** [comment]
I did accept the CLA and added another commit just to rerun the test too, still, it shows it failing

**Review by eps1lon — CHANGES_REQUESTED** [review]
They should be working. Seems like the redirects are no longer in place. See https://github.com/reactjs/reactjs.org/issues/3268#issuecomment-695974636

**Comment by manishprivet** [comment]
I checked the build, and the redirects are there as intended.
Shouldn't we put the url directly in the `<a>` tag in `/versions.js`?

Found this on Netlify Community page, posted recently [here](https://community.netlify.com/t/use-gatsby-link-w-netlify-redirects-to-external-links/20902/3)

image

**Comment by manishprivet** [comment]
Maybe this is the reason.



[Reference](https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects)

**Comment by manishprivet** [comment]
Created backup redirects by Gatsby itself

**Review by crypt096 — APPROVED** [review]

**Comment by manishprivet** [comment]
@eps1lon Can you review the PR please

**Comment by eps1lon** [comment]
I don't know enough about gatsby and the infrastructure of this docs. It would help if you could identify when and why this broke.

**Comment by manishprivet** [comment]
As mentioned in #3268, The separate documentation links on https://reactjs.org/versions/ after 16.8 are broken and redirecting to a 404 page. Apparently, the netlify redirects are not working due to some changes introduced by netlify I think. This PR fixes that by adding a redirect to the correct sites.

**Comment by BartoszKlonowski** [comment]
Hello @manishprivet!
Unfortunately, Gatsby is no longer used by the react.dev repo, so I will close this PR as outdated.
Thank you for taking the time to contribute!

**Pull request closed without merging**
