### PR TITLE
Text Display error in Go full-stack with a framework

### PR DESCRIPTION
**Pull request by nepalivai**
Fix error [27816](https://github.com/facebook/react/issues/27816)

What dose this PR do?
It fixes the issue with the landing page of the react website.

### CODE REVIEW

**Review by pwbriggs — COMMENTED** [review]
@nepalivai, I'm not sure why, but this change is making the background of the dropdown a little bit darker than the surrounding header. See screenshots below.

Before your change:
before

With your change (note the darker background around the selector:
after

**Comment by nepalivai** [comment]
@pwbriggs Interesting!! It's working fine on my end.
image

**Comment by rickhanlonii** [comment]
@nepalivai with your change I'm seeing this:

Screenshot 2024-01-05 at 11 40 57 AM

The issue is on the <option> elements, not the <select> element. Certain browser environments (e.g.. Edge on Windows) allow for styling <option> elements, whereas others (Chrome on Mac) use a default UI element.

I pushed the fix to this PR to add styles for <option> elements when the styled element is used. It works in light and dark mode:

Screenshot 2024-01-05 at 11 57 30 AM

Screenshot 2024-01-05 at 11 55 04 AM

**Comment by rickhanlonii** [comment]
Verified chrome still works as expected: 
Screenshot 2024-01-05 at 12 18 33 PM
/reactjs/react.dev/assets/2440089/bd60b8b3-37e6-44ac-8580-b08df516187d">

**Comment by rickhanlonii** [comment]
Thanks again @nepalivai!

**Pull request merged**
