### PR TITLE
fix: sandbox preview height

### PR DESCRIPTION
**Pull request by akulsr0**
### Before 
before

### After
after

### CODE REVIEW

**Review by harish-sethuraman — COMMENTED** [review]
If we reduce the height here some sandpack output screens might get a scroll to view the output. like the last one in the thinking in react page.

**Comment by akulsr0** [comment]
@harish-sethuraman The last sandbox (in thinking in react) is already having scroll in sandbox preview in current beta website? What is the expected output in this case?

**Comment by harish-sethuraman** [comment]
We have explicit height here because the sandpack's output window are killed when they move out of the screen. so the height of iframe becomes 0 how ever when we use fit content the height is shrinking and then the content move upwards. But we dont want this to happen. So we are explicitly setting the height to be 40vh.

**Comment by lunaleaps** [comment]
I'll close this PR for now.

**Pull request closed without merging**
