### PR TITLE
Add JS Party to the podcasts page

### PR DESCRIPTION
**Pull request by adamstac**
Add us to the list 🎉

### CODE REVIEW

**Comment by gaearon** [comment]
There's not as much React specific content there, is it? I guess we could say the same for JS Air so maybe we shouldn't have included it.

**Comment by adamstac** [comment]
It comes up often enough to be included as a resource IMO.

**Comment by adamstac** [comment]
Heads up!

We may not feature React as the primary conversation, but we do talk about it often. For example — we talked about [Reactivesearch](https://opensource.appbase.io/reactivesearch/) in the most recent episode ~> https://changelog.com/jsparty/20

It would be a shame to not include it. Folks looking for good JavaScript and React content and conversations would certainly enjoy our community focused podcast.

**Comment by BartoszKlonowski** [comment]
Hello @adamstac! Unfortunately the podcasts list page is no longer maintained.
Let me close this PR as outdated, but please feel invited to create new PRs to open issues.
Thank you!

**Pull request closed without merging**
