### PR TITLE
Fix issue by add arrows to articles in footer

### PR DESCRIPTION
**Pull request by Brew-Brew**
**Why?**
#964 solved by add arrows !!

**Demo**

8월-12-2019 21-56-16

**Changes**
I add arrows in footer :) So, beginners to React docs page can easily go next or prev page!

### CODE REVIEW

**Comment by zx6658** [comment]
I think this issue happen in reactjs-bot https://github.com/gatsbyjs/gatsby/issues/4693

**Comment by zx6658** [comment]
@gaearon I will be happy if this pr is cheked to merge :) If this pr is merged beginners to React docs page are can easily go next or prev page!

**Comment by zx6658** [comment]
@gaearon @joecritch  this pr will give more easier accessibility to starter of react who read docs website :) related #964 :)

**Comment by lex111** [comment]
@zx6658 hi, arrows is probably better to make clickable?

**Comment by zx6658** [comment]
@lex111 yes it is

**Comment by lex111** [comment]
@zx6658 will you do?

**Comment by zx6658** [comment]
@lex111 yeap, I alerady made change in this pr :)

**Comment by lex111** [comment]
But currently the arrows are **not** clickable :(

**Comment by zx6658** [comment]
@lex111 You are right :) I fixed it thanks :)

**Comment by zx6658** [comment]
@lex111  and i add demo in pr :)

**Comment by BartoszKlonowski** [comment]
Dears, as the issue is already closed I will close this PR as no longer required.
Please see comments in the issue.
Thank you!

**Pull request closed without merging**
