### PR TITLE
Added a new paid course to the list

### PR DESCRIPTION
**Pull request by xari**
Hi Dan,

I recently released my course on React, and wanted to add it to the list. I work for EPFL, one of two federal universities of technology in Switzerland, where we offer online courses in web development and data science that are open to all. My course is very thorough, covering the basics, as well as more advanced patterns (render-props, compound components, etc.), and even hooks. In fact, about a third of the course is devoted to teaching hooks, and the course content will continue to be updated as this hooks evolve and become mainstream.

Please check-out the link in the commit for more information about the curriculum, and feel free to email me if you have any questions (harry.anderson@epfl.ch).

Thanks, and all the best.

-Harry

### CODE REVIEW

**Comment by xaris** [comment]
Hi @gaearon,

I just wanted to follow-up to this PR since it's been about six weeks since it was opened. Please let me know if you have any questions, etc.

Thanks!

-Harry

**Comment by xaris** [comment]
Hi @gaearon, @alexkrolick , @bvaughn ,

Hope you're all doing well. This PR has been open for several months now, so I'm following-up with a friendly nudge, and also to pass-along a recent screencast recording that I made that can vouch for the quality and content of the course.

You can [find the screencast here on Medium](https://medium.com/epfl-extension-school/learn-react-custom-hooks-with-screencast-1a8c9d517576?source=friends_link&sk=7040c03279a58a79a1e548cf51f0fd19). I'd also be interested to hear if you have any comments about it too. It was fun to explore the nuances of render-props vs. custom hooks in the virtual DOM, and I'd love to know if there are any related ideas to explore in a future post.

Thanks, and all the best.

Harry Anderson
Ecole Polytechnique Fédérale de Lausanne
Swiss Federal Institute of Technology Lausanne

**Comment by xaris** [comment]
> Hi @gaearon, @alexkrolick , @bvaughn ,
> 
> Hope you're all doing well. This PR has been open for several months now, so I'm following-up with a friendly nudge, and also to pass-along a recent screencast recording that I made that can vouch for the quality and content of the course.
> 
> You can [find the screencast here on Medium](https://medium.com/epfl-extension-school/learn-react-custom-hooks-with-screencast-1a8c9d517576?source=friends_link&sk=7040c03279a58a79a1e548cf51f0fd19). I'd also be interested to hear if you have any comments about it too. It was fun to explore the nuances of render-props vs. custom hooks in the virtual DOM, and I'd love to know if there are any related ideas to explore in a future post.
> 
> Thanks, and all the best.
> 
> Harry Anderson
> Ecole Polytechnique Fédérale de Lausanne
> Swiss Federal Institute of Technology Lausanne

Hey again, @gaearon , @alexkrolick , @bvaughn —Just wanted to check-in and see if any of you had the chance to take a look at this PR yet...

Hope you're doing well,

-Harry

**Comment by BartoszKlonowski** [comment]
Hello @xari!
I'm afraid we no longer maintain that list, so I will close this PR as outdated.
However, please feel invited to create new PRs for other open issues!

**Pull request closed without merging**
