### PR TITLE
Sandpack 2.0: upgrade playgrounds

### PR DESCRIPTION
**Pull request by danilowoz**
This upgrads Sandpack to version 2.0, which brings many fixes and introduces Nodebox. Nodebox will enable us to run RSC in the future. As a part of this upgrade, I have also removed some elements, including unnecessary things, such as: 
- No more necessaries patches to fix an issue on CodeMirror syntax-highlight;
- Legacy code, such as React Devtools components (we can include later, if necessary), Sandpack preview React refs;
- Use a new approach to consume unstyled/bare Sandpack components;

### CODE REVIEW

**Comment by danilowoz** [comment]
@harish-sethuraman, can I count on you to review this PR? Things to pay attention to: 
- Syntax-highlight on the code editor: it should have a different syntax between HTML tabs and react components;
- General sandboxes layout structure;
- Decorators on the code snippets on API reference pages
- Inline syntax error: make sure they appear correct, and they are gone when fixed
- Reset code button

**Comment by harish-sethuraman** [comment]
I started to test and then this happened when I typed long text and also the horizontal scroll is also gone
Screenshot 2023-04-13 at 8 15 32 PM

**Comment by danilowoz** [comment]
Hey @harish-sethuraman, thanks for reviewing. 

CodeMirror changed how they handle the scroll, so it needed to do a few tweaks. Can you check it again? \
Hope we can get this merged soon. I was out for a couple of weeks, but I promise to be more responsive now

**Comment by kmiddleton14** [comment]
Thanks @danilowoz for this change! Could you update to the latest version and resolve the merge conflicts?

**Comment by danilowoz** [comment]
@kmiddleton14, updated! I walked through some pages testing all the sandboxes, and everything looks good

**Comment by lunaleaps** [comment]
Thanks @danilowoz for this!

My testing is also looking good! Tried out mobile. There are some issues forking the CodeSandbox when using an in-app browser but that seems consistent with current react.dev

Another thing I noticed.. which I can't reproduce anymore.. is that the "Show More/Less" ends up in the wrong place.
CleanShot 2023-09-08 at 10 25 22@2x

I've been trying to get it to reproduce with window resizing and expanding but it might've just been a fluke 🤷‍♀️

Otherwise this looks good to me!

**Pull request merged**
