### PR TITLE
Add Turkish to deployed languages

### PR DESCRIPTION
**Pull request by alioguzhan**
We are at 80% and increasing. I think we can deploy it to its subdomain.

### CODE REVIEW

**Review by lunaleaps — APPROVED** [review]

**Comment by alioguzhan** [comment]
Hey @lunaleaps, Are there any further required actions to deploy `tr.react.dev` ? It is still not live. 

Thanks

**Comment by lunaleaps** [comment]
Hmm.. not sure, let me look around / ask around if there are other steps we need

**Comment by alioguzhan** [comment]
Thank you. Someone might need to enable some things (domain settings probably) on the Vercel side.

**Comment by rickhanlonii** [comment]
@alioguzhan done, https://tr.react.dev/

**Pull request merged**
