### PR TITLE
Enhance Gallery Component with Round Robin Navigation in state-a-components-memory

### PR DESCRIPTION
**Pull request by KfirShainholtz**
This pull request introduces an enhancement to the gallery component's navigation feature, implementing a round robin mechanism to improve user interaction. With these changes, when users reach the end of the gallery and proceed, they will be seamlessly directed to the beginning, and vice versa, creating an infinite loop through the gallery items.

### Key Changes:
- Modified the `handleClick`, `handleNextClick`, and `handlePrevClick` functions to adjust the gallery index using modulo arithmetic. This change ensures that navigating beyond the bounds of the `sculptureList` array loops around to the opposite end.

#### Specific Update Example:
```js
function handleClick() {
  // Updated to support round robin navigation
  setIndex((index + 1) % sculptureList.length);
}
```

### Rationale:
Previously, the gallery component's navigation was limited, stopping at the first and last items. This behavior was identified as a limitation to user experience, prompting the need for a more fluid and intuitive navigation method. Implementing round robin navigation addresses this by allowing users to continuously cycle through the gallery items without manual intervention to reverse direction.

### Testing and Validation:
Conducted tests to ensure functionality works as expected, allowing for seamless navigation from the last item to the first, and the first to the last.
Verified that the component maintains its performance and responsiveness across different devices and browsers.
Ensured that state updates correctly without causing re-render issues or performance degradation.
This enhancement is aimed at improving the usability and accessibility of the gallery component, making the browsing experience more enjoyable and intuitive for all users. I welcome any feedback or suggestions for further improvements.

### CODE REVIEW

**Comment by KfirShainholtz** [comment]
signed my CLA, waiting for review

**Comment by pwbriggs** [comment]
@KfirShainholtz, the purpose of ["State: A Component's Memory"](https://react.dev/learn/state-a-components-memory) is to give a basic introduction to the concept of state in React. While in a real component you would *absolutely* want to have a gallery component wrap around like this, I think it just adds clutter and confusion to the examples.

Thoughts?

**Comment by KfirShainholtz** [comment]
I agree, although while encountering it I thought that the crash is a bug, 
Maybe a simpler solution/ better explanation for the behaviour will be sufficient, but lmk what you think

**Comment by pwbriggs** [comment]
I agree the crash is confusing, but I'm not sure how to mention the crash in the docs without making a big deal about it.

**Comment by KfirShainholtz** [comment]
I've added a text rephrase as a comment, please take a look, it might provide a good explanation and a crash free carousel

**Comment by pwbriggs** [comment]
I don't see your change, perhaps you forgot to `push` it?

**Comment by rickhanlonii** [comment]
The first challenge on the page is to fix the crash, so we shouldn't fix it here.

https://react.dev/learn/state-a-components-memory#challenges

**Pull request closed without merging**
