### PR TITLE
Fix homepage title

### PR DESCRIPTION
**Pull request by daochouwangu**
Fixed homepage title bug, now the homepage will display the title from `content/index.md` instead of the constant `React`.

### CODE REVIEW

**Comment by awxiaoxian2020** [comment]
@gaearon please consider this Pull Request. It's beneficial to l18n SEO. :)

**Comment by awxiaoxian2020** [comment]
cc: @sophiebits

**Review by harish-sethuraman — APPROVED** [review]
LGTM. cc: @gaearon @rickhanlonii 
Title of the home page will become `React – The library for web and native user interfaces` if this change is merged

**Comment by rickhanlonii** [comment]
@daochouwangu sorry for the delay, can you update index.md to just "React" so the title stays the same?

**Review by rickhanlonii — APPROVED** [review]

**Pull request merged**
