### PR TITLE
Adds Meteor.js as a popular alternative for full-featured framework.

### PR DESCRIPTION
**Pull request by filipenevola**
This PR adds Meteor.js to the list of popular alternatives to Next.js as full-featured frameworks.

Meteor.js has more than 53k followers on Twitter and more than 43k on GitHub (so it's popular).

By default it uses React and has very nice [integrations](https://github.com/meteor/react-packages/tree/master/packages/react-meteor-data) with it.

To install Meteor and create an app integrated with React is very simple:
``` shell
npm i -g meteor
meteor create my-app
```

The official [University](https://university.meteor.com/) course also uses React in every module.

Disclaimer: I'm the former CEO of Meteor.

### CODE REVIEW

**Review by StorytellerCZ — APPROVED** [review]

**Comment by VikR1000** [comment]
I use Meteor and React. They work together extremely well. Meteor is an amazing build tool with built-in auth and many capabilities that support fast web app development.

**Comment by regardtnel** [comment]
Meteor and React is a powerful combination.  We have used it fondly on many projects over the past 5 years.

**Review by fredmaiaarantes — APPROVED** [review]

**Comment by BartoszKlonowski** [comment]
Hello @filipenevola!
Unfortunately, we no longer maintain or keep the list of `Popular alternatives`, so let me close this PR as outdated.
Feel invited to create new PRs for open issues!

**Comment by filipenevola** [comment]
Ok, but you do have a list of frameworks listed there still, just with a different name.

image

Meteor is also Production-grade. 

I'll open a PR to include Meteor in that list, ok?

Meteor has deep integrations with React and the easiest way to achieve real-time updates with it.

Are you ok with this approach @BartoszKlonowski?

**Comment by BartoszKlonowski** [comment]
Looks like I missed that, sure! Let's do that.
You can create new PR, or we can reopen and rebase this one, let me know in case of anything.
Apologies for the confusion!

**Comment by fredmaiaarantes** [comment]
Can anyone explain why @BartoszKlonowski  comment was deleted? He suggested that we could add Meteor to the list of production-grade frameworks.

**Comment by rickhanlonii** [comment]
Sorry for the confusion, I deleted @BartoszKlonowski's comment as soon as it was posted because it made it seem like the core team approved adding Meteor to the Production-grade React frameworks section, but we haven't had a chance to discuss it. I'll post an update when we make a decision.

**Comment by filipenevola** [comment]
Ok @rickhanlonii looking forward to it.

Could you provide clarity on how this decision process works? Is it made in public? What are the criteria?

Transparency is really important here.

We (Meteor) have invested quite a lot in React.

Meteor University is React-based, tutorial, custom package, amazing real-time integrations. So we would like to understand this process as we are waiting since the end of 2022 to be included.

I think 13 months is a long time for a very straightforward decision IMO. 

Thanks in advance.

**Comment by dallman2** [comment]
I am not sure that it would be responsible to list Meteor as an alternative while its current release (2.14) still uses Node 14 (no longer receives security patches) and Fibers as its Promise system. Explicitly stating that Meteor 3 is in beta and linking to it specifically could be a solution.

**Comment by rickhanlonii** [comment]
@filipenevola, thanks for your patience. I've updated that page to clarify how we determine which frameworks we recommend, and added a new way for frameworks to apply to be added to that page which outlines the criteria we use to include a framework, and fields for framework authors to explain how they meet the criteria. 

Please feel free to send [the application link](https://github.com/reactjs/react.dev/issues/new?assignees=&labels=type%3A+framework&projects=&template=3-framework.yml&title=%5BFramework%5D%3A+) to the Meteor team, but based on my understanding of what Meteor 2.0 offers I don't think it would meet the criteria. When 3.0 is available and if it meets the criteria, then I'd be happy to review the application.

**Comment by filipenevola** [comment]
Hi @rickhanlonii, thank you for answering.

Let me address some points:

1 - My PR was opened on December 25, 2022. The last release of Node.js 14 was Feb 16, 2023, so it was maintained when I opened this PR; just many months later, it was out of LTS, so I wonder how that was the reason for this PR not being merged.

2 - The [PR](https://github.com/reactjs/react.dev/pull/6597) you merged 2 hours ago had just 1 approval and no time or call for feedback; as this is a running discussion here, on Twitter, and on Meteor Forums, why was it merged in such a hurry without time for a proper public debate on the topic?

3 - When did the React team decide to consider only "full-stack architecture" as a React production-grade framework in public? What does that mean? IMO, it makes no sense for Meteor to implement RSC. Meteor is great for many apps worldwide because it provides real-time updates to the client. We don't need RSC in Meteor apps in general. If this is an official decision it is very important and will affect many companies relying on React for years. Server components are not new, Java has done that for many years and many people switched to React because they didn't like these solutions. Is it changing now without a proper warning? Should all people and companies interested only in React on the client move away from React and find other solutions?  

I have asked a bunch of questions above and I hope this leads to some discussion in public, and not new PRs changing the docs in a very short time without time for proper discussion and feedback.

> Just to address the Meteor 3 point: Meteor 3 is already running in production in a few projects and the final release is really close so I don't think this should be taken into consideration for this discussion. Even because I still need to open the new PR but first I need to understand what is going on with React.

**Comment by rickhanlonii** [comment]
Hey @filipenevola, here are my thoughts:

Re: 1 - I don't think anyone on the team saw this PR until @BartoszKlonowski re-surfaced it. We've been heads down shipping features for the next release for the last couple of years, and honestly have not been able to triage the doc issues as much as we need to, and we're trying to get better at that now.

Re: 2 - Since you asked for what criteria we use, the intent wasn't to open a dialog about what we should include, but to document the criteria we already use to make the decision. The team is aligned on these criteria so documenting and merging them was a quick process, and I didn't want to leave you hanging without a response. As with anything we do, I'm sure there will be a lot of discussion about it, and we will iterate on the feedback.

Re 3 - I want to emphasize that this isn't a change in direction, this is the direction we chose when we recommended frameworks. If you review the PR, you can see that none of the text was new, I just moved it around and clarified it. RSCs are a new feature, and we're not requiring frameworks to support them today (e.g. Remix doesn't support them), but they do need to have plans to eventually support them and provide solutions to common problems like routing, data fetching, waterfalls. 

I totally understand that many frameworks may want to be featured, but this page is not a place to advertise every possible React framework or all frameworks that you can add React to. There are many great frameworks that offer support for React that are not listed in our guides. But when users use a framework on this page, they need to be able to use all of the features that we document in the docs, and not hit the common problems we're recommending using frameworks to avoid.

**Comment by simonwebs** [comment]
But Just want to find out. What is the way forward? Are they going to add or it does not matter either add or not.

**Comment by simonwebs** [comment]
Seriously meteor + React is awesome

**Comment by simonwebs** [comment]
What will it take from react or other frameworks over there if meteor is also added? Are we still to deal with monopoly here? Why cant it be as alternative like other ones? @rickhanlonii

**Comment by ruohki** [comment]
Meteor has first class support for react with a large ecosystem of packages as well, I do understand that frameworks won't get added which have janky support or need hacks. Meteor has been around longer than any of the others, so I really don't understand the decision to just close and dig the pr. And speaking of recommendations — gatsby is on life support and still in the list.

**Comment by dallman2** [comment]
> Meteor has first class support for react with a large ecosystem of packages as well, I do understand that frameworks won't get added which have janky support or need hacks.

Currently, I would say that the ecosystem is in limbo. There are a lot of packages that have not received updates in years that people rely on. There are many packages that have not been updated to be compatible with an upcoming major version upgrade. The current Meteor release also requires the use of Node 14, which is past EOL. These sort of issues are not indicative of a framework that needs to be pushed onto new projects right now.

I think that a lot of these things could change in the coming months and that Meteor could eventually be added to this list, but in this moment I do not think this is appropriate. I understand that this PR was created before the Meteor 3 migration started, and before Node 14 went EOL. To me, where we are today makes the context that this PR was created in effectively moot.

**Comment by simonwebs** [comment]
It will be good see it there when 3.0 is available.. not as force but as it
pleading, because your own your project we can't force you but just
consider the reality. Waiting for 3.0 it's fire🔥

**Pull request closed without merging**
